apiVersion: v1
kind: Namespace
metadata:
  name: spring-boot
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: tomcat
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

