apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nodejsdemo
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helloworld
    repoURL: https://github.com/ananyahn/helloworld.git
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
        values: |
          {{ range .Files.Lines "values-prod.yml" }}
          {{ . }}{{ end }} 
  
