apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tomcat
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tomcat
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: stable/tomcat
    repoURL: https://github.com/ananyahn/charts
    targetRevision: {{ .Values.spec.source.targetRevision }}
