apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: wordpress
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: stable/wordpress
    repoURL: https://github.com/helm/charts
    targetRevision: {{ .Values.spec.source.targetRevision }}
